// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class Test2 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    driver.get("https://www.booking.com/index.es.html?label=gen173nr-1DCAEoggI46AdIM1gEaDKIAQGYAQq4ARfIAQ_YAQPoAQGIAgGoAgO4Ap3XmeYFwAIB;sid=3a3875b686359f3cabeff0856e2938c6;keep_landing=1&sb_price_type=total&");
    driver.manage().window().setSize(new Dimension(1198, 718));
    driver.findElement(By.cssSelector(".xp__travel-purpose > .bui-checkbox__label")).click();
    driver.findElement(By.id("ss")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("ss")).sendKeys("santa marta");
    driver.findElement(By.cssSelector(".sb-autocomplete__list-with_photos > .c-autocomplete__item:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".xp__travel-purpose > .bui-checkbox__label")).click();
    driver.findElement(By.cssSelector(".xp__input-group:nth-child(2) .sb-date-field__icon")).click();
    driver.findElement(By.cssSelector(".bui-calendar__date--today")).click();
    driver.findElement(By.cssSelector(".bui-calendar__wrapper:nth-child(1) .bui-calendar__row:nth-child(6) > .bui-calendar__date:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".sb-searchbox__button")).click();
    {
      WebElement element = driver.findElement(By.linkText("Precio (más bajo primero)"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,0)");
  }
}
